included:
  - Source

disabled_rules: # rule identifiers to exclude from running
  - nesting # 禁用嵌套限制
  - large_tuple # 禁用 tuple 元素个数限制
  - statement_position # 禁用条件判断语句位置限制

opt_in_rules:
  - array_init # 使用 array 的初始化方法初始化数组
  - anyobject_protocol # 使用 AnyObject 代替 class
  - identical_operands # 比较相同元素时报错
  - implicit_return # 省略不必要的 return
  - legacy_random # 不使用 random 相关 API
  - operator_usage_whitespace # 操作符两边添加空格
  - sorted_imports # 对 import 进行排序
  - static_operator # 自定义操作符，使用 static
  - toggle_bool # 使用 toggle 代替 a = !a
  - force_unwrapping # 禁用强制解包
  - closure_end_indentation # 闭包 { } 需要有相同的缩进，可以让代码看起来更简洁
  - closure_spacing # 闭包的 { } 中间需要添加空格
  - no_extension_access_modifier # extension 前面不能有权限声明
  - multiline_arguments # 调用函数和方法时，参数应该在同一行，或者一行一个
  - multiline_parameters # 声明函数和方法时, 其参数应该在同一行上，或者每行一个
  - trailing_closure # 使用尾随闭包

function_body_length: # 函数实现长度限制
  warning: 75 # warning
  error: 100

line_length: # 每一行长度限制
  warning: 120
  ignores_interpolated_strings: true # 忽略带插值的 string
  ignores_urls: true # 忽略 url

file_length: # 文件长度限制
  warning: 500
  error: 1200

force_cast: error # 强制类型转换报错
force_try: # try! 报错
  severity: error
force_unwrapping: error

trailing_comma: # 集合类型最后一个元素后面添加逗号
  mandatory_comma: true

cyclomatic_complexity: # 函数实现复杂度限制
  warning: 20
  ignores_case_statements: true # 忽略 switch...case

identifier_name: # 变量命名规范，强制使用驼峰
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 100
  excluded:
    - id

trailing_closure:
  only_single_muted_parameter: true
